### ISSUE TITLE
12.5.10.3 - fails to clarify whether "idOfficeObject" is acceptable for custom object IDs

### ISSUE THREAD

**Issue by lawrenl** [sc34wg4/opcRevision#10]
12.5.10.3 - can it be "idOfficeObject"? I suspect not but please confirm and update if so.

**Comment by murata2makoto** [comment]
Previous editions of ISO/IEC 29500-2 did not prohibit this value.  Should we?

**Comment by RexJaeschke** [comment]
From the Milan, IT, F2F meeting of SC 34/WG4:

The spec states, “An application-defined Object element specifies application-defined information.  The Id attribute of the application-defined Object element shall be absent or have a value other than "idPackageObject".”

lawrenl (from MS) asks, “can it be "idOfficeObject"?

MS Office reserves the object ID of idOfficeObject for its digital signature in crypto work.

WG4 does not see how it can reserve that name at this late stage, especially as other implementers might use that name with different semantics.

We agreed to ask the submitter/MS experts  the following:
•	Are you using that name for this purpose?
•	Are you requesting that we reserve that name?

If possible, we'd like to get a response by mid-morning, Central Europe Time, Wednesday March 27, as we're on a tight schedule to get the revised spec out to ballot.

**Comment by lawrenl** [comment]
MS Office may use the value idOfficeObject as per https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6fc7c564-dbef-4df6-a600-de4c186c387c and it should be called out in section 12.5.10.3 for completeness.

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

Overnight, the submitter responded: “MS Office uses the value idOfficeObject as per https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6fc7c564-dbef-4df6-a600-de4c186c387c and it should be called out in section 12.5.10.3 for completeness.”

As a result, we added the following note:

[Note: Some values, such as "idOfficeObject", are known to be in widespread use.  Therefore, implementations should avoid using such values. end note]
