### ISSUE TITLE
12.9 - string comparison fails to clarify impact of locale

### ISSUE THREAD

**Issue by lawrenl** [sc34wg4/opcRevision#11]
Second validation step specified string comparison as being case insensitive but fails to clarify whether that is also locale invariant. Not sure if we need to clarify or not.

**Comment by murata2makoto** [comment]
We might want to add a note for the absence of locale-dependency.  See ["3.1.4.4 Language-specific tailoring" ](https://www.w3.org/TR/charmod-norm/#sec_language_tailoring) in W3C Character Model for the World Wide Web: String Matching.

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

The term “locale” is *not* mentioned anywhere in the OPC spec. Besides, all comparisons are ASCII-case-[in]sensitive. So, mentioning “locale” in this context would violate the media-type RFC.
