### ISSUE TITLE
D.6.2 typo and a link that is not hypertext

### ISSUE THREAD

**Issue by lawrenl** [sc34wg4/opcRevision#12]
D.6.2 - there is a link to xmldsig-core-schema.rnc that is not actually a hyperlink and there is an aa typo - should be a - "accessible as aa link https:// ... /xmldsig-core-schema.rnc"

**Comment by RexJaeschke** [comment]
Agreed!

"... and xmldsig-core-schema.rnc (accessible as aa link https://www.w3.org/TR/xmlsec-rngschema/xmldsig-core-schema.rnc)."

should have the URL as a link and with "aa" changed to "a".

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

Agreed.
