### ISSUE TITLE
OPC Table 9-1. Abstract package model components and their physical representations by Caroline

### ISSUE THREAD

**Issue by murata2makoto** [sc34wg4/opcRevision#13]
Caroline wrote:

In following up on the discussion on the interleaving comment, I bumped into something that struck me as slightly misleading in Table 9–1. Abstract package model components and their physical representations

The Physical representation text for Part media type is:
  ZIP item containing the Media Types stream described in §9.2.3.2.  See §9.3.7 for details about the ZIP item name.

The media type is not represented BY the Media Types stream, but as an entry IN the Media Types stream.  

The text in equivalent Table 10-2 in the published standard is clearer on this:
     ZIP item containing XML that identifies the content types for each part
according to the pattern described in §10.1.2.1.

A simple change would be to add "Stored in" to the beginning of the text in the current draft.

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

We agreed that in Table 9-1, for the entry Part media type to add the following text:

*Stored in the* The ZIP item containing the Media Types stream described in §9.2.3.2.  See §9.3.7 for details about the ZIP item name.
