### ISSUE TITLE
18.3.1.63 Page setup property index issue

### ISSUE THREAD

**Issue by xuri** [sc34wg4/opcRevision#14]
ISO/IEC 29500, ECMA-376 4th 18.3.1.63 Page setup property index 43 and 69 repeated explanation with `Japanese Double Postcard (200 mm x 148 mm)`, index 43 should be `Japanese Postcard  (100 mm x 148 mm)`.

**Comment by RexJaeschke** [comment]
**THIS IS NOT AN OPC ISSUE!**

This issue pertains to ECMA-376, Part 1, 4th edition, which was produced in 2012. [Re this issue, Part 1 remained *unchanged* in the 5th/2016 issue and in the current WD as at 2019-02-09.]

Part 1, 4th e.: 18.3.1.63 pageSetup (Page Setup Settings)

Attribute paperSize (Paper Size) has the following Description entries:

43 = Japanese double postcard (200 mm by 148 mm)
69 = Japanese Double Postcard (200 mm x 148 mm)

which are identical (except for the use of "by" vs. "x" and the upper vs. lowercase "d").

The poster suggests that the entry for 43 should be changed to the following:

43 = Japanese >><< postcard (>>100<< mm x 148 mm)


I also note the following:

18.3.1.64 pageSetup (Chart Sheet Page Setup)

Attribute paperSize (Paper Size) has the following Description entries:

43 = Japanese double postcard (200 mm by 148 mm)

with the values ending at 68; specifically, there is **no** 69.

Should entry 43 also be changed?
Is it OK that there are no entries > 68?


Also

21.2.2.134 pageSetup (Page Setup)

Attribute paperSize (Paper Size) (which shows the possible values in table form)

Japanese double postcard | 200 mm | 148 mm | 43

Perhaps this line should also have "double" removed and 200->100.

Again, the highest entry value is 68.


My own research on this resulted in the following:

> Hagaki Dimensions: The traditional hagaki postcard is 200 by 148 millimeters or 100 by 148 millimeters. The measurement is equivalent to 7.8 inches by 5.8 inches or 3.9 inches by 5.8 inches. Purchase hagaki paper, and you will get one of these two measurements.

This confirms the desirability to support two sizes, and suggests the poster is on the right track, by wanting to distinguish between them.

According to https://docs.microsoft.com/en-us/windows/desktop/intl/paper-sizes

> Windows 2000: This topic defines the NLS paper size types associated with the LOCALE_IPAPERSIZE constant, indicating the default paper size for a locale.
> 
> DMPAPER_JAPANESE_POSTCARD | 43 | Japanese Postcard 100 x 148 mm
> DMPAPER_DBL_JAPANESE_POSTCARD | 69 | Japanese Double Postcard 200 x 148 mm
> 

which supports the poster's proposal.

I propose we make this a new DR, and, absent evidence to the contrary, we adopt the poster's proposal.

**Comment by murata2makoto** [comment]
Excel 2017 stores hagaki (10cm * 14.8cm) as paperSize="43".  and
stores double hagaki (20cm * 14.cm) as paperSize="69".

I think that we have to fix 18.3.1.63 pageSetup (Page Setup Settings), 
18.3.1.64 pageSetup (Chart Sheet Page Setup), and 21.2.2.134 pageSetup (Page Setup).

**Comment by RexJaeschke** [comment]
Made DR 19-0017.
