### ISSUE TITLE
2. Normative references: Footnotes

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#21]
**GB-016** |   | 2 | Footnote 1) | ed | XSLT is mentioned   but is not included in the Normative References and nor is it mentioned in   the body of the specification.

Remove XSLT from   this footnote.

> Rex: Done

**GB-017** |   | 2 | Footnote 2) | ed | The purpose of   this footnote is unclear. If the intention is to refer specifically to the   constraints on compression methods, the reference should probably be   specifically to Table B.4. If the intention is to refer to general   constraints on the use of ZIP for package assembly and compression, the   footnote is unnecessary, as the same point is made normatively in the second   paragraph of 8.3.1.

Revise or remove   the footnote as appropriate.

> Rex: Deleted the footnote

   Change “ZIP file   format specification” to “ZIP Appnote” in the following clauses: 3.3.8,   8.3.3, 8.3.8.

> Rex: Done

**Comment by murata2makoto** [comment]
I agree to drop XSLT from the first footnote and also agree to drop the second footnote.

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-26.
