### ISSUE TITLE
7.2.2.2 Formatting of “I18N segment”

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#26]
**GB-029** |   | 7.2.2.2 | Para 1 | ed | The first   occurrence of “I18N segment” should probably be in italics, for consistency   with Clause 4 item (a). Alternatively, its first use should refer to where it   is defined in one of the Normative References (“I18n” is defined in the   Unicode Glossary, but “segment” is not).

If “I18n segment”   needs to be defined here, the first occurrence should be in italics.   Otherwise remove the definition and refer to where it is defined.

**Comment by RexJaeschke** [comment]
I think there is a question here *apart* from the italics issue. Where is this term defined?

**Comment by franciscave** [comment]
"I18N segment" is currently defined in 7.2.2.2, where it is then used four more times. It is also used three times in 7.5.2.3.

Ideally "I18N segment" should be defined in Clause 3. Having reviewed the Directives Part 2, specifically 16.5.9 Notes to entry, Example 2, I suggest that the following might work:

**3.x**
**I18N segment**
Unicode string

Note to entry: The constraints on the value of the Unicode string shall be stated when the term is used in Clause 7.2.2.2.

**Comment by murata2makoto** [comment]
@franciscave 

How about "Unicode string in a part name"?

I tried to  state that  "/" is used as the delimiter between I18N segments, but I cannot think of good English text

**Comment by franciscave** [comment]
The point of the note to the entry is to draw attention to the constraints on the Unicode string specified in 7.2.2.2. It is implicitly clear in 7.2.2.2 that in a part name each I18N segment is preceded by a "/". You could state this explicitly if you wish, but it simply re-states the first line of the syntax production:

> A part name comprises one or more I18N segments, each segment being prefixed by the forward slash "/".

**Comment by murata2makoto** [comment]
We agreed to introduce this definition.

3.x
I18N segment
Unicode string  in a part name

Note to entry: The constraints on the value of the Unicode string shall be stated when the term is used in Clause 7.2.2.2.

<There are no changes to Clause 7.>

**Comment by RexJaeschke** [comment]
Adopted as amended.
