### ISSUE TITLE
7.2.2.3 Equivalence of part names, and ASCII case-insensitive matching

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#27]
**GB-030** |   | 7.2.2.3 | Para 1 | ed | The first sentence   requires that the equivalence of part names “shall be determined by ASCII   case-insensitive matching”. However, this can only be a requirement for ASCII   part names, because the meaning of “ASCII case-insensitive matching” is not   normatively specified for non-ASCII code points.

Consider   re-wording the paragraph as follows:   “Equivalence of ASCII part names shall be determined by ASCII   case-insensitive matching. Such matching compares a sequence of code points   as if all ASCII code points in the range 0x41–0x5A (A–Z) were mapped to the   corresponding code points in the range 0x61–0x7A (a–z). It is recommended   that the equivalence of non-ASCII part names be determined by applying the   method for determining string identity equivalence specified in the W3C   Working Group Note on String Matching [1].”

**Comment by murata2makoto** [comment]
ASCII case-insensitive matching as defined in [Character Model for the World Wide Web: String Matching](https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/), can handle non-ASCII characters.  ASCII case-insensitive matchingt is not recommended when non-ASCII characters may appear, but OPC uses it anyway.

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-26. Agreed that in 7.2.2.3, in first para, delete the second and third sentences.
