### ISSUE TITLE
7.5.1 Duplicate definition of “relationship type”

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#32]
**GB-034** |   | 7.5.1 | Para 5 | ed | The text defines   “relationship type”, but this is already defined in clause 3.2.8.

Change the   paragraph to read:   “A relationship has a relationship type”   Alternatively,   remove the definition in clause 3.2.8.

**Comment by murata2makoto** [comment]
Agree to drop ", an absolute IRI for identifying the role of the relationship."

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-25.
