### ISSUE TITLE
8.2.3.4/5 References to “ASCII case-insensitive matching” needed

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#34]
**GB-037** |   | 8.2.3.4 | Item c) | ed | The second   sentence normatively specifies “ASCII case-insensitive matching”. This term   is normatively defined in clause 7.2.2.3. A reference would be helpful here.

We suggest following   the second sentence with: “For discussion of methods of comparison of part   names see 7.2.2.3.”   Alternatively, add   a definition of “ASCII case-insensitive matching” to clause 3.

**GB-038** |   | 8.2.3.5 | Item a) | ed | The second   sentence normatively specifies “ASCII case-insensitive matching”. This term   is normatively defined in clause 7.2.2.3. A reference would be helpful here.

We suggest   following the second sentence with: “For discussion of methods of comparison   of part names see 7.2.2.3.”   Alternatively, add   a definition of “ASCII case-insensitive matching” to clause 3.

**Comment by murata2makoto** [comment]
This term is defined in [Character Model for the World Wide Web: String Matching](https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/).  It is listed in the 
bibilography.  But since it is just an informative document (W3C Working Group Note), we should copy the definition

Here is the definition.

> ASCII case-insensitive matching compares a sequence of code points as if all ASCII code points in the range 0x41 to 0x5A (A to Z) were mapped to the corresponding code points in the range 0x61 to 0x7A (a to z).

**Comment by RexJaeschke** [comment]
We agreed to add the term to T&d. As such, no references are needed.
