### ISSUE TITLE
Use space as a thousands separator

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#38]
**ISO-042** |   | 8.3.6 | 1 | ed | ISO/IEC   Directives, Part 2, 2018, 9.1   Each group of three digits shall be   separated by a small space from the preceding digits.

Please write the number as   "65 535" if applicable.

**ISO-052** |   | B.4 | Last sentence | ed | ISO/IEC   Directives, Part 2, 2018, 9.1   Each group of three digits shall be separated by   a small space from the preceding digits.

Please write the number as   "2 147 483 647" if applicable.

**Comment by RexJaeschke** [comment]
I *really* don't like this! It seems to me that if one were going to publish a document in English (be it US or British-flavored), one would want to do so use an English locale; that is, the cultural conventions of that language.

As I think this format is French or maybe Swiss-French, could it be that someone at ISO is biased?

BTW, a few days ago, a fellow JTC 1 editor (MPEG) told me he had pushed up to the TMB a complaint about this, re ISO's failure to follow its own guidelines re cultural sensitivity. I just asked him for more info, so maybe we can cite his action in a report to ISO as to why we want to reject this.

**Comment by RexJaeschke** [comment]
I just circulated by email the paper I alluded to earlier. Unfortunately, it's an attempt to change the ISO requirement that comma be used as the decimal point in English specs, and has *nothing* to do with the thousands' separator.

**Comment by Q-Swan** [comment]
@RexJaeschke : I certainly agree that this use of a space as thousands separator would drive me mad as a reader. I assume "small space" means using one of the characters listed at https://stackoverflow.com/questions/8515365/are-there-other-whitespace-codes-like-nbsp-for-half-spaces-em-spaces-en-space/8515417#8515417 or http://jkorpela.fi/chars/spaces.html -- which one?  Would use of anything other than &nbsp; prevent line-breaks in the middle of a number in the tools we or ISO use?

Aside:  I did just run into use of the space as separator in a UK context. 
  https://www.bgs.ac.uk/products/digitalmaps/dataInfo.html
But I would probably consider map scales a domain-specific instance.

**Comment by murata2makoto** [comment]
@RexJaeschke You did the suggested changes in the latest draft you circulated, but do you intend to revisit this later?

**Comment by RexJaeschke** [comment]
@murata2makoto No! Rather than close issues I had completed, I simply marked them "Completed," so the whole group is aware of my resolution. Hopefully, that means we can get though the "Completed" issues quite quickly, closing each one.

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-25.
