### ISSUE TITLE
9.2.3.4 Bullet 4 has ambiguous text

### ISSUE THREAD

**Issue by DanielJump** [sc34wg4/opcRevision#4]
"4)	If there is a Default element with a matching Extension attribute, then the media type of the new part shall be compared with the value of the ContentType attribute. The comparison might be case-sensitive and include every character regardless of the role it plays in the content-type grammar of RFC 7231, or it might follow the grammar of RFC 7231"

Not sure about other teams, but Office performs an ASCII case-insensitive comparison on media types.

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

We agreed to change bullet 4 from:

… The comparison *might*-->*shall* be case-sensitive and include every character regardless of the role it plays in the content-type grammar of RFC 7231,

and to strike

or it might follow the grammar of RFC 7231.
