### ISSUE TITLE
11.6 Imprecise cross reference

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#40]
**ISO-050** |   | 11.6 | Step 1 | ed | ISO/IEC Directives, Part 2, 2018, 10.5   Within the text, references to   specific elements (e.g. clauses or subclauses, tables and figures) of a   referenced document shall always be dated, because subsequent editions could   result in the renumbering of such elements within the referenced document.

The reference to "Part 3, §9" is imprecise.   Please   change it to "ISO/IEC 29500-3:2015, Clause 9".

**Comment by murata2makoto** [comment]
I am wondering if we can have both a normative dated reference and an informative undated reference (in Bibliography), as well as a note such as "In the 2015 edition of ISO/IEC 29500-3, this mechanism is defined in Clause 9".

**Comment by RexJaeschke** [comment]
Change made to spec.

**Comment by murata2makoto** [comment]
I do not like a dated reference in general.  How about "ISO/IEC 29500-3" rather than "ISO/IEC 29500-3:2015, Clause 9"?

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-26 by removing the clause number.
