### ISSUE TITLE
Links to, and hosting of, external attachments

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#41]
From WG4 N0441, “Plan to Make IS 29500 Parts Comply with the ISO Style Guidelines.”

> From ISO: Annex C and D contain links to GitHub for external files. We need to use ISO’s URN to host such external attachments. For DIS, please submit the external attachment files separately, as you do for figure files. In the text, please use the following URN: http://standards.iso.org/iso-iec/29500/-2/ed-4/en (further hierarchy is possible; files will be updated to ISO’s URN in the same structure as they are submitted).

To be investigated further.

***

**ISO-053** |   | C and D |   | ed | Annex C   and D contain links to GitHub for external files. We need to use ISO’s URN to   host such external attachments.

For the next submission, please   submit the external attachment files separately, as you do for figure files.   In the text, please use the following URN:   http://standards.iso.org/iso-iec/29500/-2/ed-4/en (further hierarchy is possible;   files will be updated to ISO’s URN in the same structure as they are   submitted). The links will be created and files uploaded to the URN after   submission.   Per earlier communication, it is   noted that the plan is to address this after the DIS ballot. This comment is   added as a reminder. For any questions, please coordinate with the ISO TPM.

**Comment by RexJaeschke** [comment]
@murata2makoto: As you own the schema master files, I'm assigning this to you. Please provide me with the files. I'll then ask ISO what the final URLs will be, so I can change the links.

**Comment by murata2makoto** [comment]
OK.  I will take care of this.

**Comment by murata2makoto** [comment]
Please replace

- `https://sc34wg4.github.io/OOXMLSchemas/Part2/`

by

- `http://standards.iso.org/iso-iec/29500/-2/ed-4/en/`

and also replace

- `https://sc34wg4.github.io/OOXMLSchemas/documentation/Part2/`

by

- `http://standards.iso.org/iso-iec/29500/-2/ed-4/en/OpenPackagingConventions-XMLSchema-Documentation/`

.

We store schemas and html files at these locations when we go for an FDIS.

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-25.
