### ISSUE TITLE
Foreword: Various issues

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#44]
**ISO-056** |   | Foreword |   | ed | The Foreword shall   use the up-to-date generic text which is provided in the Simple template in   the Drafting standards section on iso.org:   https://www.iso.org/drafting-standards.html

Text updated in   the DIS_edit file.

> Rex: Done

**GB-057** |   | Foreword | Para 7, Bullet 1 | ed | The clause   ‘Conformance’ is Clause 5 in the DIS text. The DIS correctly includes   Normative References as Clause 2 in accordance with the Directives Part 2.   The current (2018) edition of the ISO/IEC Directives Part 2 makes no mention   of a requirement to include the Conformance clause at a particular position. 

Remove this bullet   point.

> Rex: Done

**GB-058** |   | Foreword | Para 7, Bullet 11 | ed | Pack IRIs are   defined in Clause 7 in the DIS text.

Re-word this   bullet point, e.g. “...Pack IRIs are now defined in Clause 7.”

> Rex: Done

**GB-059** |   | Foreword | Para 7, Bullet 12 | ed | The phrase   “externally defined schemas” is missing a hyphen.

“...externally-defined   schemas.”

> Rex: Rejected; while our style is to hyphenate compound adjectives, we follow the widely accepted practice of *not* doing that when the first word is an adverb ending in "ly". See [Wikipedia](https://en.wikipedia.org/wiki/Compound_modifier#Exceptions_2).

**GB-060** |   | Foreword | Para 7, Bullet 13 | ed | The use of “has”   in this sentence is grammatically incorrect.

“...have been dropped.”

> Rex: Done

**GB-061** |   | Foreword | Para 7, Bullet 14 | ed | This is not a   proper sentence as worded.

Re-word this   bullet point, e.g. “Requirements around streaming consumption have been   dropped.”

> Rex: Done

**GB-062** |   | Foreword | Para 7, Bullet 5 | ed | The clause ‘Abstract   package model’ is Clause 7 in the DIS text. 

Re-word this   bullet point, e.g. “Clause 7 (Abstract package model, Clause 8 in preceding   editions)...”

> Rex: Done

**GB-063** |   | Foreword | Para 7, Bullet 6 | ed | This is not a   proper sentence as worded.

Re-word this bullet   point, e.g. “The option for media type to be an empty string has been   removed.”

> Rex: Done

**GB-064** |   | Foreword | Para 7, Bullet 7 | ed | The clause   ‘Physical package model’ is Clause 8 in the DIS text.

Re-word this   bullet point, e.g. “Clause 8 (Physical package model, Clause 9 in preceding   editions)...”

> Rex: Done

**GB-065** |   | Foreword | Para 7, Bullet 8 | ed | The clause ‘Core   properties’ is Clause 9 in the DIS text.

> Rex: Done

Re-word this   bullet point, e.g. “Clause 9 (Core properties, Clause 10 in preceding editions)...”

**GB-066** |   | Foreword | Para 7, Bullet 9 | ed | The clause   ‘Digital signatures’ is Clause 11 in the DIS text.

Re-word this   bullet point, e.g. “Clause 11 (Digital signatures, Clause 12 in preceding   editions)...”

> Rex: Done

**Comment by RexJaeschke** [comment]
I looked at each of the issues above, and added my recommendations.

**Comment by RexJaeschke** [comment]
Applied all edits to resolve ISO-056.

**Comment by franciscave** [comment]
I think that you need to delete the original paragraph at the top of page viii: "ISO/IEC 29500-2 was prepared by ISO/IEC JTC 1, Information technology, Subcommittee SC 34, Document description and processing languages." The inserted paragraph that follows it appears to be a replacement for the original paragraph.

**Comment by RexJaeschke** [comment]
WG4 approved, as amended by Francis, on 2020-08-26.
