### ISSUE TITLE
G. Add an entry to the Bibliography

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#45]
**ISO-067** |   | G |   | ed | ECMA-376:2006 is informatively referenced. 

Please list ECMA-376:2006 in the Bibliography.

**Comment by RexJaeschke** [comment]
Note that Bibliography entry numbers are hard-coded in our spec, so any changes to the order (to maintain alphabetical order [something we don't do currently]) would require changing other entry references.

**Comment by murata2makoto** [comment]
@RexJaeschke Do we only have to put this reference at the end of Bibliography?

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-25.
