### ISSUE TITLE
Foreword: Proposed addition

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#49]
**US-074** |   |   |   | Ge | As the   foreword states, “This fourth edition preserves all previous functionality   and adds no new functionality.”  The   changes since ISO/IEC 29500-2:2012 include corrections and many   clarifications.  All editions of   ISO/IEC 29500-2 have permitted non-ASCII characters in names for parts in a   compliant package, but this edition provides more complete detail on how to   handle them, based on the IETF RFC for Internationalized Resource Identifiers   (IRIs).  Where appropriate, normative   references have been updated to use undated or more recent versions of other   standards.

Please   consider.

**Comment by murata2makoto** [comment]
In the foreword, we have a bulleted list of changes.  One bullet is:

> Clause 8 (Abstract package model) has been completely rewritten.  In particular, (1) pack IRIs are defined in this clause rather than in an annex, (2) a new subclause, "Resolving relative references", was added; (3) part Relationship parts and package Relationship parts are distinguished; and (4) base IRIs are clearly defined.

How about "(5) handling of non-ASCII characters in part names have been clarified on the basis of RFC 3987"?

**Comment by murata2makoto** [comment]
Should we also add "(6) Where appropriate, normative references have been updated to use undated or more recent versions of other standards."?

**Comment by franciscave** [comment]
I agree with Murata-san's proposed additions to the Foreword, but they should be new bullet-points, and not be included in the numbered sub-list under the Clause 8 bullet-point. Murata-san's point (6) should be the first bullet-point, as it relates to Clause 2. Murata-san's point (5) relates most strongly, I believe, to Clause 7, so should come immediately before the Clause 8 bullet-point.

**Comment by murata2makoto** [comment]
@franciscave 

My (6) should indeed be the first bullet-point.  We should also clearly state that this is about Clause 2.

My (5) is about Clause 7 in the new text but about Clause 8 in the previous edition.

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-26.

The new (6) will become the first bullet in the existing list. (5) stays as (5).
We'll recast the new entries words along the lines of the existing ones.
