### ISSUE TITLE
9.2.4 Interleaving comment by Rex

### ISSUE THREAD

**Issue by DanielJump** [sc34wg4/opcRevision#5]
"Pieces in physical packages shall occur in their natural order for optimal efficiency."

Office doesn't implement interleaving, but we agree with the requirement that pieces should be in order.

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

We agreed to keep the change to “shall”.

§9.2.5.2, “Logical Item Names”, contains a grammar production for PieceNumber, which is a non-negative integer. As such, we agreed to the following change:

Pieces in physical packages shall occur in their natural *piece-number* order

and strike 

for optimal efficiency.
