### ISSUE TITLE
7.2.2.2 Improving readability of code style

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#51]
*US-079* |   | 7.2.2.2   and throughout |   | Ed | In the   previous edition, the style for code (as for the ABNF rules here) was much   easier to read.

Please fix   the style for an easier read.

**Comment by RexJaeschke** [comment]
Rejected: Previously, we set all code fragments and blocks using the font "Consolas;" however, ISO *requires* us to use "Courier New," which we have.

**Comment by murata2makoto** [comment]
I at least would like to discuss this topic with ISO.  Surely, their choice of fonts is unfriendly to aged guys like us...

**Comment by murata2makoto** [comment]
It might be possible to introduce an alternative monospaced font in addition to ‘Courier New’.

**Comment by RexJaeschke** [comment]
We'll extend the Q. to ISO w.r.t alternate fonts from Issue #25 to include code and code fragment styles.

**Comment by RexJaeschke** [comment]
We have been told by ISO that there are no acceptable constant-width alternatives to Courier New, so we're stuck with that.
