### ISSUE TITLE
Terms and definitions: General

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#56]
From WG4 N0441, “Plan to Make IS 29500 Parts Comply with the ISO Style Guidelines.”

> From ISO: Please remove the second paragraph and reproduce the terms and definitions listed; RFE 3986 and RFC 2046 should be given as the SOURCE at the end of each terminological entry. See ISO/IEC Directives, Part 2, 2018, 16.5.10.  

To be investigated further.

> From ISO: Only terms that are used shall be listed, exactly as they appear in the text. Please check throughout the document to make sure that the terms listed are all used. For example, “package, abstract” is not used in the text; the term should be changed to “abstract package” to be consistent with its usage.

OK, will do.

**Comment by RexJaeschke** [comment]
## Issue 1

Can someone help with this?

## Issue 2 

All the entries of the form "<text1>, <text2>" will need to be written as "<text2> <text1>". However, I don't see that such a change would force any re-ordering (and subsequent re-numbering) of terms. [That is, we are *not* using alphabetic ordering.] For example:

> **3.1.3
> behavior**
> ...
> **3.1.4
> behavior, application-defined
> behavior, implementation-defined**
> ...
> **3.1.5
> behavior, unspecified**
> ...

becomes

> **3.1.3
> behavior**
> ...
> **3.1.4
> application-defined behavior
> implementation-defined behavior**
> ...
> **3.1.5
> unspecified behavior**
> ...

**Comment by murata2makoto** [comment]
Issue 1

We need "MIME media type" and "MIME entity", and nothing else from MIME RFCs.

"MIME media type" is explained in 7.2.3, which is basically borrowed from RFC 2046.  This term is extensively used in 29500-2.

>Each part shall have a MIME media type, as defined in RFC 2046, to identify the type of content in that part, consisting of a top-level media type and a subtype, optionally qualified by a set of parameters.  Media types of OPC-specific parts defined in this document shall not contain parameters. 

"MIME entity" is used in an example in 8.2.3.1 and nowhere else.  So, we do not have to worry about this.

I am wondering if we can simply stop mentioning MIME RFCs in our Terms and Definitions.

**Comment by RexJaeschke** [comment]
I resolved Issue 2 with edits to the spec.

**Comment by RexJaeschke** [comment]
The text cited from ISO (before the DIS ballot stated, so came via email and *not* a DIS comment) was:

> Please remove the second paragraph and reproduce the terms and definitions listed; RFE 3986 and RFC 2046 should be given as the SOURCE at the end of each terminological entry. See ISO/IEC Directives, Part 2, 2018, 16.5.10.  

The "second paragraph" referred to here was the second paragraph of the "Terms and definitions" clause we had through WD3.8, which follows:

> <Para 1> For the purposes of this document, the terms and definitions given in RFC 3986 and the following apply. Other terms are defined where they appear in italic typeface. Terms explicitly defined in this document are not to be presumed to refer implicitly to similar terms defined elsewhere.

> <Para 2> The terms *base URI*, *relative reference*, *URI scheme*, *authority*, *fragment*, *path*, *query*, and *segment* are used in accordance with RFC 3986.  The term *media type* is used in accordance with RFC 2046.

What we have in the DIS ballot draft is the following, single paragraph:

> For the purposes of this document, the terms and definitions given in RFC 2046, RFC 3986, and the following apply.

Perhaps the issue has gone away!

**Comment by murata2makoto** [comment]
@RexJaeschke  Can we simply say

> For the purposes of this document, the following terms and definitions apply.

**Comment by RexJaeschke** [comment]
WG4 approved Murara-san's words on 2020-08-26.
