### ISSUE TITLE
9.3.5 Mapping Zip Item Names...

### ISSUE THREAD

**Issue by DanielJump** [sc34wg4/opcRevision#6]
"For all ZIP items, except for MS-DOS ZIP items (as defined in the ZIP Appnote) that are not MS-DOS files, their names shall be mapped to logical item names."

This could be more clear - the purpose is to exclude zip items which represent MS-DOS special items: 'empty directory' and 'volume label'. If the "version made by" is 0, then we exclude zip items with "external file attributes" with bits 3 or 4 set.

appnote.txt only includes information about MS-DOS values for "external file attributes".

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

We agreed to replace the first paragraph

For all ZIP items, except for MS-DOS ZIP items (as defined in the ZIP Appnote) that are not MS-DOS files, their names shall be mapped to logical item names.

with

The names of all ZIP items shall be mapped to logical item names, except for items that do not represent files.

We deleted the existing note, and added the following new note after the opening paragraph:

[Note:  For some file systems, the ZIP Appnote provides further information on ZIP items that are recognized as files. end note]
