### ISSUE TITLE
Alternative to "should" for use inside informative text

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#60]
7.2.2 (and other occurrences) [Example: Suppose that an abstract package contains a part named "/é/Å/foo", where é is 'LATIN SMALL LETTER E WITH ACUTE' (U+00E9) and Å is 'ANGSTROM SIGN' (U+212B).  For it not to be weakly derivable, no other parts in that abstract package **should** have names such as "/É" and "/É/Å", where É is 'LATIN CAPITAL LETTER E' (U+0045) followed by 'COMBINING ACUTE ACCENT' (U+0301) and Å is 'LATIN CAPITAL LETTER A WITH RING ABOVE' (U+00C5).  end example]

What word can we use here instead of "should"?

**Comment by murata2makoto** [comment]
Hmm.  Paragraphs preceding such examples describe normative requirements using "should" or some normative words.  Examples show how such requirements are applied to specific characters or strings.  If we use a different word, will the reader mistakenly think that the requirements are lifted for the specific case?

**Comment by RexJaeschke** [comment]
For completeness, 7.2.2.3 contains the following:

> [Example: If an abstract package contains a part named "/a", the name of another part in that abstract package **must not** be "/a" or "/A". end example]

> [Example: Suppose that an abstract package contains a part named "/segment1/segment2/…/segmentn".  For it not to be derivable, other parts in that abstract package **must not** have names such as "/segment1", "/SEGMENT1", "/segment1/segment2", "/segment1/SEGMENT2", or "/segment1/segment2/…/segmentn-1". end example]

We agreed to change both "must not" to "cannot".

ISO objects to the "should" in the following 3 places, by saying "Recommendations are not allowed in EXAMPLEs.
Please change the paragraph to normal body text."

> [Example: If an abstract package contains a part named "/é", where é is 'LATIN SMALL LETTER E' (U+0065) followed by 'COMBINING ACUTE ACCENT' (U+0301), the name of another part in that abstract package **should not** be "/é", where é is 'LATIN SMALL LETTER E WITH ACUTE' (U+00E9), or "/É", where É is 'LATIN CAPITAL LETTER E WITH ACUTE '(U+00C9). end example]

> [Example: If an abstract package contains a part named "/Å", where Å is 'ANGSTROM SIGN' (U+212B), the name of another part in that abstract package **should not** be "/Å" where Å is 'LATIN CAPITAL LETTER A WITH RING ABOVE' (U+00C5) because U+212B and U+00C5 are normalized to the same character sequence. .end example]

> [Example: Suppose that an abstract package contains a part named "/é/Å/foo", where é is 'LATIN SMALL LETTER E WITH ACUTE' (U+00E9) and Å is 'ANGSTROM SIGN' (U+212B).  . For it not to be weakly derivable, no other parts in that abstract package **should** have names such as "/É" and "/É/Å", where É is 'LATIN CAPITAL LETTER E' (U+0045) followed by 'COMBINING ACUTE ACCENT' (U+0301) and Å is 'LATIN CAPITAL LETTER A WITH RING ABOVE' (U+00C5).  .end example]

Re ISO's suggestion, can we just remove the Example tags and keep the words we have rather than trying to argue with ISO about leaving the words as is?

**Comment by RexJaeschke** [comment]
We discussed this on today's call. We'll leave resolution until we get feedback from ISO w.r.t allowing a sentence to contain "for example" without being an Example.

**Comment by RexJaeschke** [comment]
Replaced 2x "must not" with "cannot". Three Examples containing "should [not]" are no longer examples.
