### ISSUE TITLE
Cannot have more than one space after a sentence-ending period/fullstop

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#61]
ISO editors reported this in our spec; can anyone find where this is a requirement in the Part 2 Directives?

**Comment by RexJaeschke** [comment]
I think we should ask ISO to confirm that this is a requirement.

# Proposal 

Assuming that this is a requirement, it should be easy to implement by searching for all periods followed by two spaces, with the search done repeatedly just in case there are more than two. (Note that the ISO editor marked at least some occurrences as tracked changes, but we can't be sure they found them all.)

**Comment by murata2makoto** [comment]
You did this change with the exception of one in 11.5.1.  Do you intend to revisit this issue later?

**Comment by RexJaeschke** [comment]
WG4 approved on 2020-08-25.
