### ISSUE TITLE
Can/Should we use ISO's Word file as our base for changes?

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#62]
ISO gave us back a Word file with tracked changes they want us to make, and Word comments they want us to address. Many (perhaps most) of these were also reported by ISO as comments on the ballot. It is clear ISO intends us to revise and return that same file; however, that is *not* an absolute requirement, and at least one other JTC 1 editor told me he never does this because of deficiencies in that file.

Note that it's not just a matter of using/not using ISO's file as our base for making corrections for this edition, it's also about what we'll use for the base for the next edition. We don't want to have to make two sets of edits: one on the file for publication and the same again on a separate "new base" file.

## Questions for ISO

1. Do we have the option of using a base file *other* than the one they gave us?

1. What tooling is applied to the file we send back for review/publication, and is the process different if we use their file as a base or some other file. For example, their file has stripped out all soft-returns we specifically put there to inhibit bad page breaks. If we add those back in and the file gets re-processed with tools, won't that strip them out again? If so, how can we ever get certain formatting actions to stick?

## Pros

1. Easy to adopt any tracked changes proposed by ISO; otherwise they would all have to be applied to a different file.

## Cons

1. The file has all cross-reference links hard-coded. (See Issue #63.)
1. The auto-generated number machinery used for "Terms and definitions" items has been removed.
1. All soft-returns (used to inhibit bad page breaks) have been removed.
1. We lose all trace of the usage of the "Notation conventions" styles.

**Comment by murata2makoto** [comment]
If we send a different document, ISO CS will have to apply the same preprocessing before the conversion to STS.  I can imagine that this is time-consuming.

**Comment by murata2makoto** [comment]
I have been in contact with ISO CS.

I learned a lot about the production toolchain.  

1. Submitted/input files: Word document, reference PDF, revisable graphics.
2. Word document is opened inhouse. Our Word has eXtyles, a plugin that applies "styles" to text and allows for correct XML mark-up (the "styles" correspond to elements).
3. We "style"/mark-up the entire document via eXtyles. The software also runs various other processes (spelling correction, font audits, whitespace clean-up, among other things).
4. We export the XML from eXtyles/Word.
5. We create the PDF from the XML (via the Typefi platform, which involves XML, Indesign, scripts, and PDF export from Indesign).
6. We clean the Word file of eXtyles software content.
7. Output files: the 'clean' Word document, the generated PDF.

This explains why runs that reference empty "Element" and "Attribute" styles appear in the Word document from ISO.   The same applies to table styles.  That Word document is NOT created from STS.

This also makes clear that tweeking styles in the Word document from ISO has no impact on the final layout.

I also learned that their conversion to STS ignores style information.  Layout information specified by styles are sometimes used, and sometimes not.  But after obtaining layout information (such as font specification) from styles, style references are ignored.

![Toolchain](https://user-images.githubusercontent.com/5499496/85671504-e4829b80-b6fc-11ea-8686-06647d64e641.png)

**Comment by RexJaeschke** [comment]
## 2020-07-08 Teleconference

Based on Murata-san’s presentation of the ISO process it seems that

- If we use ISO’s Word file as the base for our corrected edition, ISO will not have to apply the same preprocessing to that file.  The file will be handled by eXtyles and Typefi.
- If we use our Word file as the base for our corrected edition, ISO will apply the same preprocessing to our Word file. As such, we should not re-add any formatting information, as that will be stripped out again.

ISO has said that it is impossible to make cross references updatable (via fields of MS Word).  But Murata-san explained that his experimental implementation makes clear that it is possible.  He sent the result to ISO but has not received any response. 
In either case, we’ll need to make a final pass over the document to manually handle bad page breaks, perhaps removing justification from some paragraphs, as well as some other manual edits.

**Comment by RexJaeschke** [comment]
From: Rex Jaeschke <rex@RexJaeschke.com> 
Sent: 2020-08-09 21:07
To: CHEN Yvonne <CHEN@iso.org>
Subject: Question re the Publication of IS 29500-2

Dear Ms. Chen,

You, via the ISO/IEC JTC 1/SC 34 Secretary, sent me the Word draft of DIS 29500-2 produced by ISO. 

I have a simple question: Instead of editing the Word document you sent me and returning that, can I instead apply the required edits to the Word draft that I originally submitted for DIS ballot and re-submit that?

Given that the ISO Word draft of DIS 29500-2 is missing important information (such as cross-referencing links and other things being hard-coded), I will *not* be able to use that as the base document for the next revision of this specification. I’d very much like to avoid having to revise your draft as well as my own, which, of course, would be double the work.

I’d appreciate an answer by the end of Friday August 21, as we have a meeting a few days later to discuss this project, and so I can start creating the final draft for publication now that the ballot has passed.

Kind regards,

Rex Jaeschke, project editor of IS 29500


From: CHEN Yvonne <CHEN@iso.org> 
Sent: Monday, August 10, 2020 3:38 AM
To: Jaeschke Rex Mr <rex@rexjaeschke.com>
Subject: RE: Question re the Publication of IS 29500-2

Dear Rex,

Thanks for your message.

**Yes, you have the option to use your own base file as long as all the edits are incorporated. But please note that after your submission, ISO CS will have to apply the processing again for XML conversion.** 

Please be assured that after the next submission, styles like cross-referencing links will be checked against your submitted PDF before sending it out for FDIS and/or Proof review. In the ISO production process, the PDF at the DIS stage is generated without being checked by the ISO editor, in order to open the DIS ballot as quickly as possible after the committee's submission. But for the FDIS submission, the procedure is different: the ISO editor will review the text, produce the PDF file, and make sure the layout is correct.

Best regards,
yvonne chen 
editorial programme manager | standardization department | iso central secretariat | phone: +41 (0) 797261512|

**Comment by RexJaeschke** [comment]
From: Rex Jaeschke <rex@RexJaeschke.com> 
Sent: Thursday, August 13, 2020 4:08 PM
To: SC 34 WG4 (e-SC34-WG4@ecma-international.org) <e-SC34-WG4@ecma-international.org>
Subject: GREAT NEWS re Producing a Draft of 29500-2 for FDIS

We can apply all our edits to our original DIS draft and resubmit that!

This means
1.	Our final submission will be usable directly as the base of the next edition.
2.	We don’t have to deal with the loss of cross-reference link info, table/figure numbers, and such all being hard-coded in the version ISO publishes.
3.	We won’t have to undo all the edits ISO staff made to (incorrectly) make namespace references hyperlinks.
4.	We get to redefine the styles for elements names, attribute names and values, and type names differently, so they make it through the ISO tools rather than being ignored.
5.	We do *not* have to plug anything midway into the ISO tools process. They’ll just take our FDIS submission and re-process it. 

Based on this feedback, I have started applying the edits ISO requires along with issues we’ve already closed. I will distribute the best version I can make a week or so in advance of the first day of our upcoming call series.

Rex

**Comment by RexJaeschke** [comment]
From: MURATA Makoto <eb2m-mrt@asahi-net.or.jp> 
Sent: Thursday, August 13, 2020 6:46 PM
To: Rex Jaeschke <rex@rexjaeschke.com>
Cc: SC 34 WG4 <e-SC34-WG4@ecma-international.org>
Subject: Re: GREAT NEWS re Producing a Draft of 29500-2 for FDIS


Rex,

Thanks for the update.

2020年8月14日(金) 5:07 Rex Jaeschke <rex@rexjaeschke.com>:
Below is my question to our ISO editor and her reply. 
 
We can apply all our edits to our original DIS draft and resubmit that!
 
This means
1.	Our final submission will be usable directly as the base of the next edition.
Yes.

| 2. We don’t have to deal with the loss of cross-reference link info, table/figure numbers, and such all being hard-coded in the version ISO publishes. 

Yes.

| 3.  We won’t have to undo all the edits ISO staff made to (incorrectly) make namespace references hyperlinks. 

Yes.

| 4.  We get to redefine the styles for elements names, attribute names and values, and type names differently, so they make it through the ISO tools rather than being ignored. 

This requires changes to the ISO toolchain, but I am certainly interested in this negotiation.  A good topic for the planned meeting with ISO.

| 5.We do *not* have to plug anything midway into the ISO tools process. They’ll just take our FDIS submission and re-process it.

Well, she wrote " ISO CS will have to apply the processing again for XML conversion".  Let's see what happens.

Regards,
Makoto

**Comment by RexJaeschke** [comment]
Regarding Item 4, "We get to redefine the styles for elements names, attribute names and values, and type names differently, so they make it through the ISO tools rather than being ignored." 

Murata-san responded: "This requires changes to the ISO toolchain, but I am certainly interested in this negotiation. A good topic for the planned meeting with ISO."

*I disagree!* Here's my rationale:

We currently use our own styles "Code" and "Code fragment", respectively, for code blocks and inline code fragments. They used to be defined as font "Consolas". As ISO requires constant-width text to be set using "Courier New", I change both styles to that font, and **those fonts made it through the ISO process, being preserved in the Word they send back to us!** So, it seems that custom styles are *not* completely ignored; if they are defined using a font that ISO accepts, their impact is retained.

As discussed in Issue #25, we have styles "Element", "Attribute", "Attribute value", and "Type, XSD Base Type", and based on the rationale above, if we redefine those to be fonts acceptable to ISO, we solve the problem and keep the styles.

**Comment by murata2makoto** [comment]
Ah, if you replace "Consolas" by "Courier New", the font is recognized by the converter from Word to STS.
