### ISSUE TITLE
Cross-Reference Links in ISO Word File are All Hard-Coded!

### ISSUE THREAD

**Issue by RexJaeschke** [sc34wg4/opcRevision#63]
See Issue #62 .

As these links have been reduced to hard-coded text in the ISO Word file, going forward, we can't add or change links easily, unless they are somehow (presumably grammatically) restored. [Think, "impact on Part 1 revision!"]

Interestingly, the links are hyperlinks in the PDF that went out to DIS ballot, so it is clear that PDF was *not* generated from the Word they gave us back.

**Comment by murata2makoto** [comment]
This is no longer a show stopper since it is possible to convert cross-references in ISO-created documents to updatable fields.  
My program can already handle cross-references to clauses and subclause.  Cross-references to figures and tables can also be addressed.

**Comment by murata2makoto** [comment]
On June 14, I sent the output of my program to ISO and asked if it is usable for further processing.  I have not heard from ISO about it yet.

**Comment by RexJaeschke** [comment]
This problem is avoided, as we're permitted to go back and use our original spec, edit that, and resubmit it. See Issue #62.

Ready to close without action.
