### ISSUE TITLE
Section 12 : references to "XML-Signature Syntax and Processing" aren't links

### ISSUE THREAD

**Issue by lawrenl** [sc34wg4/opcRevision#7]
Should references to "XML-Signature Syntax and Processing" really be links? Either informative or normative, depending on where the reference is?

**Comment by murata2makoto** [comment]
Since this is a normative reference, it is shown in Clause 2.

**Comment by RexJaeschke** [comment]
I agree with Murata-san; no hyperlink is necessary here, so this issue can be closed without action.

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

Correct, they are not, and they should not be! Closed without action.
