### ISSUE TITLE
12.5.7 RelationshipReference element SourceId comment issues

### ISSUE THREAD

**Issue by lawrenl** [sc34wg4/opcRevision#8]
RelationshipReference element has a table with SourceId as the attribute. There are several issues with this section:
- There is a beginning quote with no end quote in the description column.
- It does not state whether the attribute is optional or required (although the reference does clarify).

**Comment by murata2makoto** [comment]
This attribute is required, as shown in the complex type CT_RelationshipReference.  In ISO/IEC 29500-1 and -4, we sometimes repeat what is specified in schemas but we often do not do so.  In 29500-2, I can go either way.

**Comment by murata2makoto** [comment]
The end quote should be added.  Good catch.

**Comment by RexJaeschke** [comment]
Regarding the missing close-quote, I agree.

... simple type of the W3C Recommendation “XML Schema Part 2: Datatypes.

should be

... simple type of the W3C Recommendation “XML Schema Part 2: Datatypes>>"<<.

**Comment by RexJaeschke** [comment]
2019-03-25 F2F Meeting in Milan:

Agreed to add the missing close-quote, which is also missing in SourceType’s Description of §12.5.8.

Action: Murata-san will examine all attributes in OPC to see which ones we specify in narrative as well as in schema. Depending on what he finds we might make a change here.

**Comment by murata2makoto** [comment]
In 29500-2, we usually specify whether attributes are optional or mandatory in narrative as well as in schemas.  Thus, I propose to add "This attribute is required." as the second paragraph of the
SourceId attribute description in 12.5.7 and also as the second paragraph of the SourceType attribute description in 12.5.8.

Moreover, in 12.5.13 (SignatureTime Element), 12.5.14 (Format Element), and 12.5.15 (Value Element), we have to specify that they shall have no attributes.

**Comment by RexJaeschke** [comment]
Discussion from the 2019-04-24 WG4 Teleconference:

We agreed to make these changes.
